### ISSUE TITLE
XM does not work with a certain hardware combo.

### ISSUE THREAD

**Issue by coopzone-dc** [PickledDog/rc-640k#1]
When using this card with an SC114 motherboard and latest RomWBW, some interaction to do with timing stops XM Xmodem working.
See
https://groups.google.com/g/rc2014-z80/c/vmlrYldJLMQ

It's not really an issue but just thought you may want to be aware. It's bound to be a one off as no one else would try this anyway!

I'm not really after a fix or anything.

All the best.

Derek

**Comment by PickledDog** [comment]
A curious issue indeed! I'll try to reproduce it here and see what I can come up with
-Wesley

**Comment by PickledDog** [comment]
This proved to be a timing issue in the 6850 ACIA code. Thanks to some phenomenal investigation from yourself, Wayne Warthen, Bill Shen, and Phillip Stevens, we were able to corner it and get a fix checked into RomWBW at https://github.com/wwarthen/RomWBW/commit/3e6120e0fada4456a72f2044176c47b691fa94a9 . This resolves the issue.
